---
- name: config new subdomain script for ddns update task scheduler
  hosts: all
  become: true
  gather_facts: true
  #vars:
  #  add_record: true
   
  tasks:
  
  - name: add new A record
    include_role:
      name: add_record
    when: add_record|bool
  
  - name: add new ddns update script
    include_role:
      name: ddns_update
