---
# run installed script to stop bitnami service
- name: stop service
  command: 'sudo /opt/bitnami/ctlscript.sh stop'

# renew the certificate using lego
- name: renew certificate
  command: 'sudo /opt/bitnami/letsencrypt/lego --tls --email="{{cert_email}}" --domains="{{cert_domain}}" --path="/opt/bitnami/letsencrypt" renew --days 90'

# run installed script to start bitnami service
- name: start service
  command: 'sudo /opt/bitnami/ctlscript.sh start'

- name: get new cert info
  community.crypto.x509_certificate_info:
    path: "{{cert_path}}"
  register: new_cert_info
